swagger: "2.0"
info:
  version: "0.0.1"
  title: Terminal Commands App
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /api/commands:
    
    x-swagger-router-controller: commands_service
    get:
      description: Returns commands of users
      # used as the method name of the controller
      operationId: getCommands
      responses:
        "200":
          description: Success
          schema:
           type: array
           items:
            $ref: "#/definitions/Command"
        "500":
          description: Error
          schema:
            $ref: "#/definitions/CommonResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  
  
  
  Command:
   properties:
    category:
     type: string
    text:
     type: string
    detail:
     type: string
     
  
  CommonResponse:
    properties:
      code:
       type: number
      message:
        type: string
