swagger: "2.0"
info:
  version: "0.0.1"
  title: Terminal Commands App
# during dev, should point to your local machine
host: localhost:8080
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
  
tags:
- name: "Commands"
  description: "Commands' services"
- name: "Category"
  description: "Category' services"  

  
  
  
  
paths:
  /api/commands:
    x-swagger-router-controller: commands_service
    get:
      tags:
       - "Commands"
      description: Returns all commands 
      operationId: getCommands
      parameters:
      - in: query
        name: language
        description: Choose a language -> TR,ENG,FRA
        required: true
        type: string
      responses:
        "200":
          description: Success
          schema:
           type: array
           items:
            $ref: "#/definitions/Command"
        "500":
          description: Error
          schema:
            $ref: "#/definitions/CommonResponse"
    
    
    
  /api/categories:
    x-swagger-router-controller: category_service
    get:
      tags:
      - "Category"
      description: Returns category list
      operationId: getCategories
      parameters:
      - in: query
        name: language
        description: Choose a language -> TR,ENG,FRA
        required: true
        type: string
      responses:
       "200":
        description: Success
        schema:
         type: array
         items:
          $ref: "#/definitions/Category"
       "500":
         description: Error
         schema:
          $ref: "#/definitions/CommonResponse"
          
          
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  
  Category:
   properties:
    id:
     type: string
    name:
     type: string
  
  
  Command:
   properties:
    category:
     $ref: "#/definitions/Category"
    text:
     type: string
    detail:
     type: string
     
  
  CommonResponse:
    properties:
      code:
       type: number
      message:
        type: string
        
 

